services:
  streamlit:
    image: blagnac
    build: ./
    ports:
        - 8084:1234
    volumes:
      - ./:/app/
    command: streamlit run --server.port 1234 streamlit/Introduction.py
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    restart: unless-stopped
    networks:
      - nginx-proxy

#  scraper:
#    image: blagnac
#    build: ./
#    profiles: ["back"]
#    volumes:
#      - ./:/app/
#    command: python scrape.py

networks:
  nginx-proxy:
    external: true
