services:
  streamlit:
    image: blagnac
    build: ./
    volumes:
      - ./:/app/
    command: streamlit run --server.port 1234 streamlit/Introduction.py
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blagnacoscope.rule=Host(`${DOMAIN}`)"
      - "traefik.http.services.blagnacoscope.loadbalancer.server.port=1234"
      - "traefik.http.routers.blagnacoscope.entrypoints=websecure"
      - "traefik.http.routers.blagnacoscope.tls.certresolver=letsencrypt"
      - "traefik.http.routers.blagnacoscope.tls=true"

#  scraper:
#    image: blagnac
#    build: ./
#    profiles: ["back"]
#    volumes:
#      - ./:/app/
#    command: python scrape.py
